# Generated by Django 4.0.4 on 2022-05-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={},
        ),
        migrations.AlterField(
            model_name='companies',
            name='company_name',
            field=models.CharField(default='Company: TBA', max_length=60),
        ),
    ]
