# Generated by Django 4.0.4 on 2022-05-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
