# Generated by Django 4.0.4 on 2022-05-21 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_companies_options_alter_companies_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
