# Generated by Django 4.0.4 on 2022-05-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_companies_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
