# Generated by Django 4.0.4 on 2022-05-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_jobpost_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
