# Generated by Django 4.0.3 on 2022-04-08 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('portfolio', models.CharField(max_length=100)),
                ('interests', models.CharField(choices=[('FE', 'Front-End'), ('BE', 'Back-End'), ('FS', 'Full-Stack'), ('MD', 'Mobile Dev'), ('DO', 'Dev Ops'), ('SI', 'Security & Infrastructure')], max_length=2)),
                ('previousoccupation', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('IA', 'Immediately Available'), ('AW', 'About 2 Weeks'), ('MT', 'Moving Target')], max_length=2)),
                ('workstatus', models.CharField(choices=[('AL', 'Actively Looking'), ('AC', 'Actively Curious'), ('HE', 'Happily Employed')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TechSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('proficiency_level', models.CharField(choices=[('BG', 'Beginner'), ('IM', 'Intermediate'), ('AD', 'Advanced')], max_length=2)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.member')),
            ],
        ),
    ]
