# Generated by Django 4.0.3 on 2022-04-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='linkedin',
            field=models.CharField(max_length=50),
        ),
    ]
