# Generated by Django 4.0.3 on 2022-04-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_member_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='linkedin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='workstatus',
            field=models.CharField(choices=[('AL', 'Actively Looking'), ('AC', 'Just Curious'), ('HE', 'Happily Employed')], max_length=2),
        ),
    ]
