# Generated by Django 4.0.3 on 2022-04-08 00:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_member_linkedin_alter_member_workstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FE', 'Front-End'), ('BE', 'Back-End'), ('FS', 'Full-Stack'), ('MD', 'Mobile Dev'), ('DO', 'Dev Ops'), ('SI', 'Security & Infrastructure')], max_length=17),
        ),
    ]
