# Generated by Django 4.0.3 on 2022-04-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_member_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techskills',
            name='name',
            field=models.CharField(max_length=65),
        ),
    ]
